[tool.poetry]
name = "langfuse"
version = "0.1.0"
description = "A client library for accessing langfuse"
authors = ["langfuse <developers@langfuse.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
wrapper = {path = "wrapper", develop = true}
pytest = "^7.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
